spring:
  application:
    name: skillservice

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      data-source-properties:
        reWriteBatchedInserts: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        # Critical for @ElementCollection batching
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false



opensearch:
  host: ${OPENSEARCH_HOST}
  port: ${OPENSEARCH_PORT}
  user: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  scheme: https
  index: skills



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}


      instance:
        prefer-ip-address: true          #  Use IP instead of hostname
        hostname: localhost

server:
  port: ${PORT:8081}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  properties:
    security.protocol: ${KAFKA_SECURITY_PROTOCOL}
    sasl.mechanism: ${KAFKA_SASL_MECHANISM}
    sasl.jaas.config: >
      org.apache.kafka.common.security.scram.ScramLoginModule required
      username="${KAFKA_USERNAME}"
      password="${KAFKA_PASSWORD}";
  topic:
    skill-events: skill-events
    skill-updated: skill-updated

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"


app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 2592000000

auth:
  service:
    url: ${AUTH_SERVICE_URL}

user:
  profile:
    url: ${USER_PROFILE_URL}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.postgresql.jdbc.PgStatement: TRACE