spring:
  application:
    name: eurekaServer



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

    instance:
      prefer-ip-address: true          #  Use IP instead of hostname
      hostname: localhost

server:
  port: 8761
