spring:
  application:
    name: gatewayservice


  cloud:
    gateway:
      server:
        webflux:
          routes:
            #  Auth Service - NO FILTER (public endpoints)
            - id: authService
              uri: lb://AUTHSERVICE
              predicates:
                - Path=/auth/**

            - id: skillservice
              uri: lb://SKILLSERVICE
              predicates:
                - Path=/api/search/**




            #  User Profile Service - PUBLIC endpoints (no auth required)
            - id: userprofile-public-exists
              uri: lb://USERPROFILE
              predicates:
                - Path=/api/users/*/exists
                - Method=GET

            - id: userprofile-public-search
              uri: lb://USERPROFILE
              predicates:
                - Path=/api/users/search
                - Method=GET

            - id: userprofile-public-get
              uri: lb://USERPROFILE
              predicates:
                - Path=/api/users/*
                - Method=GET
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/users/(?<segment>.*)
                    replacement: /api/users/${segment}

            # User Profile Service - PROTECTED endpoints (auth required)
            - id: userprofile-protected
              uri: lb://USERPROFILE
              predicates:
                - Path=/api/users/**
              filters:
                - AuthenticationFilter

            #  Skills Service - WITH FILTER (protected)
            - id: skillservice
              uri: lb://SKILLSERVICE
              predicates:
                - Path=/api/skills/**
              filters:
                - AuthenticationFilter


            - id: bookingservice
              uri: lb://BOOKINGSERVICE
              predicates:
                - Path=/api/bookings/**
              filters:
                - AuthenticationFilter


            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notifications/**



            - id: chat-service
              uri: lb://CHAT-SERVICE
              predicates:
                - Path=/api/chat/**,/api/messages/**
              filters:
                - AuthenticationFilter












eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


      instance:
        prefer-ip-address: true          #  Use IP instead of hostname
        hostname: localhost

app:
  jwt:
    secret: "bXktc3VwZXItc2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tMjAyNA=="
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 2592000000



server:
  port: 8888